### ISSUE TITLE
SIGSEGV building from source

### ISSUE THREAD

**Issue by MrHuu** [masterfeizz/Quake2CTR#6]
I've been trying to build Quake2CTR from source, but i can't seem to be able to reproduce a fully functional build.

I'm using the latest release of libctru 2.1.1 and have the required libraries available. 
As well as the latest build of picaGL from the revamp branch.

The project builds without issues.
But when the produced binaries (both .3dsx and .cia) are executed, the application raises an segmentation fault when loading cinematics.

Without cinematics the builds seems to run ok, both unmodified source and mods.

A debug build without optimization gives the following information:

```c
Thread 1 received signal SIGSEGV, Segmentation fault.
0x001ff4a8 in _malloc_r ()

Thread 1 (Thread 421 (TLS: 0x1ffb2000, running, dynamic prio.: 48, static prio.: 48, ideal core: 0, running on core 0)):
#0  0x001ff4a8 in _malloc_r ()
#1  0x001b8190 in Draw_StretchRaw (x=0, y=0, w=400, h=240, cols=320, rows=240, data=0x871e710 '\001' <repeats 200 times>...) at /home/mrhuu/SharedFolder/_git/Quake2CTR/./ref_gl/gl_draw.c:365
#2  0x00108d8c in SCR_DrawCinematic () at /home/mrhuu/SharedFolder/_git/Quake2CTR/./client/cl_cin.c:565
#3  0x0011af68 in SCR_UpdateScreen () at /home/mrhuu/SharedFolder/_git/Quake2CTR/./client/cl_scrn.c:1542
#4  0x0010727c in CL_Frame (msec=4011) at /home/mrhuu/SharedFolder/_git/Quake2CTR/./client/cl_main.c:2452
#5  0x00145d04 in Qcommon_Frame (msec=4011) at /home/mrhuu/SharedFolder/_git/Quake2CTR/./qcommon/common.c:1636
#6  0x001d4cc4 in main (argc=0, argv=0x0) at /home/mrhuu/SharedFolder/_git/Quake2CTR/./ctr/sys_ctr.c:415

```

Are there any updates to picaGL not pushed yet?
Or did i mess up somewhere else along the line?

Anyhow, a huge thank you for updating your already awesome ports to be even more awesome!
Being able to play with music makes it even better and it even supports rogue and xatrix music when enabled in settings.

I can't thank you enough for your dedication to show how it's done, instead of my lame ports.. your work has been a true source of inspiration.

**Comment by masterfeizz** [comment]
Sorry for the delay. The latest changes to picaGL should fix that.

**Comment by MrHuu** [comment]
Thank you very much, latest build does run as intended.
